ALTER TABLE articles ADD COLUMN IF NOT EXISTS priority_level INTEGER DEFAULT 0;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS viral_score INTEGER DEFAULT 0;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS duplicate_of_id TEXT;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS image_path TEXT;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS caption_json JSONB;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS posted_platforms_json JSONB;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS best_platform TEXT;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS retry_count INTEGER DEFAULT 0;
